export const ON_LOGIN_SUCCESSFUL = "ON_LOGIN_SUCCESSFUL"
export const ON_LOGIN_FAILED = "ON_LOGIN_FAILED"
export const ON_LOGOUT = "ON_LOGOUT"

export const ON_ACCESS_TOKEN_REFRESHED = "ON_ACCESS_TOKEN_REFRESHED"
